### PR TITLE
add oceanbase's Oracle mode support.

### PR DESCRIPTION
**Pull request by borgle**
Implement OracleDialect, and add OceanBase support.

### CODE REVIEW

**Review by pavel-henrykhsen — APPROVED** [review]
LGTM, thank you!

**Review by tdspora — APPROVED** [review]
LGTM, thank you!

**Review by pavel-henrykhsen — APPROVED** [review]
LGTM

**Review by henrykp — APPROVED** [review]
LGTM

**Review by henrykp — APPROVED** [review]

**Comment by borgle** [comment]
Why can't auto-merge when all is approved? confused.

**Comment by henrykp** [comment]
I have no idea :(
I've set an e-mail to the owner, but got no reply :(

**Comment by daneshpatel** [comment]
> I have no idea :( I've set an e-mail to the owner, but got no reply :(
Sorry Pavel for delay was tied up in other issue, I have provided access to you please accept invitation.
Will also provide Pypi access for this project

**Pull request merged**
